name: img2img
channels:
  - pytorch
  - nvidia
dependencies:
  #- python=3.10
  - numpy
  - matplotlib
  - pandas
  - torch
  - torchvision
  - torchaudio
  #- pytorch-cuda=11.8
  - lightning
  - sunpy
  - setproctitle
  - tqdm
  - albumentations
  - pyyaml
  - tensorboard
  - diffusers
  - aiapy