name: "171_304 to 193 (Pix2PixHD)"

data:
  ext: npy
  image_size: 256
  train:
    input_dir: /data/datasets/BBDM/train/A
    target_dir: /data/datasets/BBDM/train/B
    batch_size: 4
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
  val:
    input_dir: /data/datasets/BBDM/val/A
    target_dir: /data/datasets/BBDM/val/B
    batch_size: 1
    shuffle: false
    num_workers: 1
    pin_memory: false
    drop_last: false
  test:
    input_dir: /data/datasets/BBDM/test/A
    target_dir: /data/datasets/BBDM/test/B
    batch_size: 1
    shuffle: false
    num_workers: 1
    pin_memory: false
    drop_last: false

model:
  generator:
    name: R2AttU_Net # default_generator # AttU_Net
    args:
      input_ch: 3
      target_ch: 1
      n_gf: 64
      n_downsample: 4
      n_residual: 9
      norm_type: InstanceNorm2d
      padding_type: 'reflection'
      trans_conv: True
      t: 2 # only used in R2AttU_Net
  discriminator:
    name: default_discriminator
    args:
      input_ch: 3
      target_ch: 1
      n_df: 64
      ch_balance: 1
      n_D: 2

params:
  ema:
    active: True
    rate: 0.999
  optimizer:
    name: Adam
    args:
      lr: 0.00001 # 0.00001 
      betas: [0.5, 0.999]
  grad_clip:
    clip: True
    max_norm: 1.0
  loss:
    LSGANcriterion:
      name: MSELoss
      args: 
        lambda_LSGAN: 2.0
    FMcriterion:
      name: L1Loss
      args:
        lambda_FM: 10.0
    CCcriterion:
      name: Concordance
      args:
        n_CC: 4
        lambda_CC: 5.0
  num_epochs: 50
  log_per_iteration: 50
  save_img_per_epoch: 1
  save_state_per_epoch: 10
  save_top_k: -1
  seed: 42
  float32_matmul_precision: "high"
  accelerator: "cuda"
  devices: [0]
  precision: "32-true"
  strategy: "ddp"
  output_dir: ./results/sdo/pix2pixCC/default
  resume_from: null