name: "171_304 to 193 (Pix2Pix, ResNet + PatchGAN)"

data:
  ext: npy
  image_size: 256
  train:
    input_dir: /data/datasets/BBDM/train/A
    target_dir: /data/datasets/BBDM/train/B
    batch_size: 4
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: false
  val:
    input_dir: /data/datasets/BBDM/val/A
    target_dir: /data/datasets/BBDM/val/B
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: true
    drop_last: false
  test:
    input_dir: /data/datasets/BBDM/test/A
    target_dir: /data/datasets/BBDM/test/B
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: true
    drop_last: false

model:
  generator:
    name: resnet
    args:
      input_nc: 3
      output_nc: 1
      ngf: 64
      norm_layer: instance
      use_dropout: false
      n_blocks: 6
      padding_type: reflect
      init_type: normal
      init_gain: 0.02
  discriminator:
    name: patchgan
    args:
      input_nc: 4 # input_nc + output_nc
      ndf: 64
      n_layers: 3
      norm_layer: instance
      init_type: normal
      init_gain: 0.02

params:
  optimizer:
    name: Adam
    args:
      lr: 0.0002
      betas: [0.5, 0.999]
  loss:
    generator:
      name: L1Loss
      lambda: 100
    discriminator:
      name: BCEWithLogitsLoss
  num_epochs: 50
  log_per_iteration: 10
  save_img_per_epoch: 1
  save_state_per_epoch: 50
  save_top_k: -1
  seed: 42
  float32_matmul_precision: "high"
  accelerator: "cuda"
  devices: [0]
  precision: "32-true"
  strategy: "auto"
  output_dir: ./results/sdo/default_lightning
  resume_from: null